/*
* generated by Xtext
*/
package at.mcreiseii.jpas.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JPasOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
