/*
 * generated by Xtext
 */
package at.mcreiseii.jpas;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JPasRuntimeModule extends at.mcreiseii.jpas.AbstractJPasRuntimeModule {

}
