/*
* generated by Xtext
*/
package at.mcreiseii.jpas.ui.contentassist;

import at.mcreiseii.jpas.ui.contentassist.AbstractJPasProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JPasProposalProvider extends AbstractJPasProposalProvider {

}
