/*
 * generated by Xtext
 */
package at.mcreiseii.jpas.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JPasUiModule extends at.mcreiseii.jpas.ui.AbstractJPasUiModule {
	public JPasUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
