/*
 * generated by Xtext
 */
package at.mcreiseii.jpas.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JPasExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return at.mcreiseii.jpas.ui.internal.JPasActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return at.mcreiseii.jpas.ui.internal.JPasActivator.getInstance().getInjector("at.mcreiseii.jpas.JPas");
	}
	
}
