/*
* generated by Xtext
*/
package at.mcreiseii.jpas.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.mcreiseii.jpas.services.JPasGrammarAccess;

public class JPasParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JPasGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.mcreiseii.jpas.parser.antlr.internal.InternalJPasParser createParser(XtextTokenStream stream) {
		return new at.mcreiseii.jpas.parser.antlr.internal.InternalJPasParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public JPasGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JPasGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
