/*
* generated by Xtext
*/
package at.mcreiseii.jpas;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JPasUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.mcreiseii.jpas.ui.internal.JPasActivator.getInstance().getInjector("at.mcreiseii.jpas.JPas");
	}
	
}
